### PR TITLE
frontend: Fix broken cluster settings navigation

### LINKED ISSUE #4041: Cluster settings 404
## Describe the bug
When clicking on "Cluster settings" on the login screen, a 404 page is returned.
When reloading the page without changing anything else, the settings are shown.

## To Reproduce
Steps to reproduce the bug:
1. Open the Headlamp page without logging in
2. Click on "Cluster settings"
3. 404 Page is shown
4. reload page
5. settings are shown

## Environment
 - Installation type: In-Cluster via Helm/ArgoCD
 - Headlamp Version: 0.36.0
 - Other: exposed via ingress-nginx

### PR DESCRIPTION
**Pull request by emmanuel-ferdman**
## Summary

The "Cluster settings" button on the token and authentication pages was broken - clicking it would either navigate to the home page or fail to load the settings page properly. The issue was that the link URL included query parameters in the wrong place, which React Router couldn't handle during client-side navigation. This PR fixes the button to properly navigate to the cluster settings page with the correct cluster selected.

## Related Issue

Fixes #4041

## Changes

- Fixed AuthChooser non-error case to use `settingsClusterHomeContext` with proper search prop.
- Fixed AuthChooser error case to pass the cluster parameter that was missing from original fix.
- Fixed Auth token page to use same pattern.
- Updated snapshots to reflect correct URLs.
- Omit empty `?c=` query param when no cluster is set, producing cleaner URLs.

## Steps to Test

1 Navigate to `/c/<cluster-name>/token`
2. Click "Cluster settings" link
3. Verify it navigates to `/settings/cluster?c=<cluster-name>` and loads correctly

## Notes for the Reviewer

This PR is a follow-up to issue #2404 and PR #2405 - the original fix was incomplete (removed cluster parameter entirely instead of passing it correctly).

### CODE REVIEW

File: frontend/src/components/authchooser/index.tsx [hunk 1]
```diff
@@ -303,7 +303,7 @@ export function PureAuthChooser({
                 <ColorButton onClick={handleTokenAuth}>{t('Use A Token')}</ColorButton>
               </Box>
               <Box m={2} textAlign="center">
-                <Link routeName="settingsCluster" params={{ clusterID: clusterName }}>
+                <Link routeName="settingsClusterHomeContext" search={`c=${clusterName}`}>
```
[the remark this answers is not in the document]
Comment (emmanuel-ferdman) [reply frontend/src/components/authchooser/index.tsx]: This pattern is consistent with the existing codebase - see `createRouteURL.tsx:98`, `SettingsCluster.tsx:138`, `ClusterSelector.tsx:38` which all use `?c=${cluster}` without encoding. If URL encoding is needed, it should be addressed codebase-wide in a separate PR.

**Comment by illume** [comment]
@emmanuel-ferdman thanks. Can you please squash the commits into one?

You can add the two parts into the context so it's easier for people to see where the change is:
> frontend: auth: authchooser: Fix broken cluster settings navigation

For this repo we do not use signed-off, so please remove that from the commit message?

File: frontend/src/components/authchooser/index.tsx (hunk 1 above)
Comment (illume) [inline frontend/src/components/authchooser/index.tsx]: I'm pretty sure this works:
```
search={{ c: clusterName }
```

This way it avoids enoding/injection issues. Can you please try that?

Comment (emmanuel-ferdman) [reply frontend/src/components/authchooser/index.tsx]: @illume Thanks for the review! Tried it - doesn't work. The `Link` component passes search directly to React Router, which expects a [string](https://github.com/kubernetes-sigs/headlamp/blob/main/frontend/src/components/common/Link.tsx#L128). Passing an object causes `search.charAt is not a function` error. We'd need to update [`search`](https://github.com/kubernetes-sigs/headlamp/blob/main/frontend/src/components/common/Link.tsx#L43) to accept objects and convert via `URLSearchParams`. Want me to add that change to this PR? It will probably require to do something like:
```typescript
+ const searchString = typeof search === 'object' ? new URLSearchParams(search).toString() : search;
...
   return (
     <MuiLink
       component={RouterLink}
       to={{
         pathname: createRouteURL(routeName, params),
-        search,
+        search: searchString,
         state,
       }}
       {...otherProps}
 ...
 ```

Comment (illume) [reply frontend/src/components/authchooser/index.tsx]: Ok, cool! Yes, please add it to this PR. In a separate commit first if possible?

btw. please rebase to remove the merge commit?

Comment (emmanuel-ferdman) [reply frontend/src/components/authchooser/index.tsx]: @illume sure, fixed 😄
