### PR TITLE
frontend: hide empty top bar overflow menu on small screens

### LINKED ISSUE #4462: Top bar shows unnecessary empty overflow menu on mobile-sized screens
## Describe the bug

On small-width (mobile-sized) screens, the top bar shows a three-dot (overflow) menu icon that opens an empty menu. This empty menu is unnecessary, consumes valuable screen space, and makes the UI look inconsistent.
The expected behavior is that the three-dot menu should be hidden or removed entirely when there are no actions to display.

## To Reproduce

Steps to reproduce the bug:

1. Open Headlamp in a web browser.
2. Resize the browser window to a small width (mobile-sized screen).
3. Observe the top bar section.
4. Click on the three-dot (overflow) menu.
5. See that an empty menu is displayed, occupying space without providing any functionality.

Yes (I will propose a PR).

## Additional Context

The empty overflow menu appears only on small screen sizes and does not provide any actions. Removing or conditionally hiding the three-dot menu when it contains no items would improve UI consistency and usability, especially on mobile devices.
This issue impacts visual clarity and wastes limited screen space on smaller displays.

### PR DESCRIPTION
**Pull request by d1vyanshu-kumar**
## Summary

This PR fixes a UI bug by hiding the empty three-dot (overflow) menu in
the top bar on mobile-sized screens. The change prevents rendering an
unnecessary empty menu, reducing wasted space and improving UI
consistency on small-width layouts.

## Related Issue

Fixes #4462

## Changes

* Updated the top bar overflow menu to hide the three-dot icon when no
  actions are available on small screens
* Prevented rendering of an empty overflow menu container
* Improved responsive UI behavior for mobile-sized layouts

## Steps to Test

1. Run Headlamp locally.
2. Resize the browser window to a mobile-sized width.
3. Observe the top bar section.
4. Verify that the three-dot (overflow) menu is no longer visible.
5. Confirm that no empty menu appears and the layout looks consistent.

## Screenshots (if applicable)

Screenshot 2026-01-27 at 3 03 22 PM

## Notes for the Reviewer

* The change is limited to a small UI adjustment and does not affect
  existing functionality on larger screen sizes.
* Happy to update this to a conditional render or breakpoint-based
  approach if preferred.

### CODE REVIEW

**Comment by sniok** [comment]
well it's not always empty, we can't just always hide it

**Comment by d1vyanshu-kumar** [comment]
@sniok, could you please share a bit more detail on how this is supposed to work? Based on that, I can optimize the implementation so the UI looks consistent. I’d really appreciate your guidance on this.

**Comment by illume** [comment]
@d1vyanshu-kumar some times there are items in there.

I think a good fix would only hide it if there are no items in the menu to display.

You can see it with an item in there with:
```
npm run storybook
```

See the "TopBar" in the search field, and you can see it with different states.

A fix should work when there are items in there and when there are not.

**Comment by d1vyanshu-kumar** [comment]
@sniok @illume Could you please review my latest commit?

**The Problem:**

The issue had two root causes:

1. **Nested MenuItems** - The SETTINGS and USER actions were wrapped in `<MenuItem>`, but `AppBarActionsMenu` already wraps actions in `<MenuItem>`. This created nested `<li><li></li></li>` elements, which caused the empty box appearance.

Screenshot 2026-01-29 at 8 53 49 PM


2. **SettingsButton returns null when no cluster** - The `SettingsButton` component returns `null` when there's no cluster context. But the filter was checking `React.isValidElement(<SettingsButton />)` which returns `true` (it's a valid element), even though the component renders nothing at runtime. This caused an empty MenuItem to appear.

**The Fix:**

- Removed the `<MenuItem>` wrappers from SETTINGS and USER actions (AppBarActionsMenu handles this)
- Made SETTINGS action conditional: `isClusterContext ? <SettingsButton /> : null`
- Fixed a typo in the filter: `typeof action === 'function'` → `typeof action.action === 'function'`

Now the three-dot menu only shows when there are actual items to display.





https://github.com/user-attachments/assets/abcd04e1-973b-4aa2-88a5-2901cc1edd62

**Comment by d1vyanshu-kumar** [comment]
@illume Everything looks good now. Please take a look.  
Most of the changes are due to formatting; the actual changes are small.  
Thank you!

**Review by illume — CHANGES_REQUESTED** [review]
Thanks for this!

Please see the [git commit guidelines](https://headlamp.dev/docs/latest/contributing#2-follow-commit-guidelines) and look at other git log messages.

Something like:
> frontend: TopBar: Fix display of empty tool menu on small screens


Can you please squash the commits? I think it should be 1 for this change.


There's a github check failing. Please run checks locally like these:
```
npm run tsc
npm run lint
npm run format
npm run test
```

**Comment by d1vyanshu-kumar** [comment]
@illume Could you please guide me on this? 

When I run `npm run test`, multiple test cases fail initially. Then, when I press `u` to update the snapshots, it passes almost all tests but:
 
1. **It adds many `.storyshot` files to the commit section** - Should I include all of these in my commit? 
 2. **One unrelated test still fails:**
    ```
    src/lib/k8s/api/v2/multiplexer.test.ts > WebSocket error handling > should handle polling timeout
    ```
    This appears to be a WebSocket timeout issue, not related to my TopBar fix. Should I ignore this for my PR?
 
 Please let me know if I should commit all the updated storyshot files or if there's another approach I should take.

**Comment by illume** [comment]
You can update the snapshots like this:
```
npm run test -- -u 
```

The websocket failure should like it might be an existing intermittent bug unrelated to your changes. I guess you would encounter it on the main branch?

Yeah, if there are changed storyshots from your changes please commit them too. It's also a good idea to review the html to see if it's basically what you were expecting, or if there are strange changes.

**Comment by d1vyanshu-kumar** [comment]
@illume Thank you for the guidance! I've made the following changes:

- Squashed all commits into 1 commit  
- Updated the commit message to follow the guidelines: `frontend: TopBar: Fix display of empty tool menu on small screens`  
- Ran `npm run test -- -u` to update snapshots  
- Verified the WebSocket timeout test (`multiplexer.test.ts`) also fails on the `main` branch, so it appears to be a pre-existing intermittent issue unrelated to my changes  

Please let me know if this looks good to you or not.

**Comment by d1vyanshu-kumar** [comment]
@illume Thanks for the feedback! I've updated the snapshots.

Turns out the issue was a Node version mismatch; I'm on v22 locally while CI uses v20, which was causing the snapshots to render differently. I've regenerated them now to match CI's environment.

Please review it at your convenience. Thank you!

**Review by illume — APPROVED** [review]
🎉 thanks!

**Comment by illume** [comment]
Some snapshot tests failed again.

I'm trying to update the snapshots on my local machine... see if these ones work on CI.

**Comment by illume** [comment]
The test is passing now.

ps. @d1vyanshu-kumar it might be worth wiping your node_modules and installing with "npm ci". What OS are you using I wonder?

File: frontend/src/components/App/TopBar.tsx [hunk 1]
```diff
@@ -146,7 +148,10 @@ export default function TopBar({}: TopBarProps) {
   const logoutCallback = useCallback(async () => {
     if (!!cluster) {
       await logout(cluster);
-      queryClient.removeQueries({ queryKey: ['clusterMe', cluster], exact: true });
+      queryClient.removeQueries({
+        queryKey: ['clusterMe', cluster],
+        exact: true,
+      });
```
Comment (joaquimrocha) [inline frontend/src/components/App/TopBar.tsx:154]: Why was this reformatted? Was this done by our formatting?

**Comment by d1vyanshu-kumar** [comment]
> Not sure why this patch also reformats part of the topbar file, but I guess it's okay since the tests are fine.

@illume Thank you so much for fixing the snapshots and approving the PR! 

To answer your question: I'm on macOS running Node v22.14.0. I'll definitely use npm ci instead of npm install next time to ensure cleaner dependency installation.

I really appreciate your help and patience throughout this process. Learned a lot!

File: frontend/src/components/App/TopBar.tsx (hunk 1 above)
Comment (d1vyanshu-kumar) [reply frontend/src/components/App/TopBar.tsx:154]: Yes, the reformatting was done by our formatting tools. When I ran `npm run frontend:lint` it automatically reformatted those lines to match the project's style guide.
