### PR TITLE
frontend: RollbackButton: move hook calls before early return to fix rules-of-hooks

### LINKED ISSUE #5191: frontend: RollbackButton: Fix `react-hooks/rules-of-hooks` — `useState`, `useLocation`, `useTranslation`, `useEventCallback`, and `useCallback` are called conditionally (after a guard clause). Move all hook calls to the top of the component before any conditional returns. File: `frontend/src/components/common/Resource/RollbackButton.tsx`

### PR DESCRIPTION
**Pull request by jedbillyb**
Fixes #5191

Moves all hook calls (`useState`, `useLocation`, `useTranslation`,
`useEventCallback`, `useCallback`) to the top of `RollbackButton`
before the early return guard clause, satisfying rules-of-hooks.

`resource` is now derived as `RollbackableResource | null` before the
guard, and TypeScript can narrow it correctly after.

Steps to test:
- Run `npx eslint src/components/common/Resource/RollbackButton.tsx` - no warnings

### CODE REVIEW

**Review by illume — CHANGES_REQUESTED** [review]
For this one too... another PR was merged and there's now a git conflict. Are you able to fix the git conflict?

**Comment by jedbillyb** [comment]
@illume fixed!

File: frontend/src/components/common/Resource/RollbackButton.tsx [hunk 1]
```diff
@@ -34,63 +34,37 @@ import ActionButton, { ButtonStyle } from '../ActionButton';
 import AuthVisible from './AuthVisible';
 import RollbackDialog from './RollbackDialog';
 
-/**
- * Interface for resources that support rollback.
```
Comment (skoeva) [inline frontend/src/components/common/Resource/RollbackButton.tsx:38]: why are these comments being removed?

**Review by skoeva — CHANGES_REQUESTED** [review]
can you squash the merge commits and address the CI failures?

**Comment by jedbillyb** [comment]
Updated this PR to address the CI/type issues in RollbackButton.

- Kept hooks before the early return (rules-of-hooks)
- Fixed nullable `resource` typing after the guard (for docs/plugins TS builds)

Latest local checks:
- npm run frontend:lint
- npm run frontend:tsc

Could you please re-review? I also resolved the related review threads.

**Review by illume — APPROVED** [review]
🎉 thanks!
