### PR TITLE
frontend: secret/Details: Fix react-hooks/rules-of-hooks violations

### LINKED ISSUE #5241: frontend: secret/Details: Fix `react-hooks/rules-of-hooks` — the `section()` helper function calls `React.useState`, `React.useRef`, and `React.useEffect` but is a plain function. Same pattern as configmap/Details — rename to PascalCase component or refactor. File: `frontend/src/components/secret/Details.tsx`

### PR DESCRIPTION
**Pull request by iashutoshyadav**
## Summary

This PR fixes `react-hooks/rules-of-hooks` violations by extracting the inline `section()` helper in `secret/Details.tsx` into a proper React component `SecretDataSection`.

## Related Issue

Fixes #5241

## Changes

- Extracted inline `section()` helper function into a named `SecretDataSection` React component
- Fixed hook calls (`useState`, `useRef`, `useEffect`) that were inside a plain function — moved them into the new component body
- Removed all `// eslint-disable-next-line react-hooks/rules-of-hooks` suppressions
- Refactored `SecretDataSection` to own its `useTranslation` and `useDispatch` hooks directly

## Steps to Test

1. Navigate to any Secret detail page in Headlamp
2. Verify the Data section renders correctly with editable fields and a Save button
3. Edit a secret value and click Save — confirm the change is applied
4. Run `npx eslint --rule '{"react-hooks/rules-of-hooks": "error"}' src/components/secret/Details.tsx` and confirm no violations

## Screenshots (if applicable)
image
image

## Notes for the Reviewer

- No behavior change intended. Hook logic (state, ref, effect) is identical — only the enclosing function is now a proper PascalCase React component.
- Same pattern as the configmap/Details fix.

### CODE REVIEW

**Comment by iashutoshyadav** [comment]
Hii @illume 

 I’ve opened a PR to fix the react-hooks/rules-of-hooks issue in secret/Details.tsx.

I refactored the inline section() helper into a proper React component SecretDataSection, ensuring that all hooks (useState, useRef, useEffect) are now used inside a valid component. I followed the same pattern used in configmap/Details to keep consistency.

The change is minimal and does not affect existing functionality—UI and behavior remain unchanged.

I’d appreciate your feedback and suggestions for improvement. Thanks!

**Comment by iashutoshyadav** [comment]
hii @skoeva 

Thanks for the suggestions
Both issues have been addressed:

- `item.data` is now deep-cloned and typed as `Record<string, string>` to avoid shared references and remove the need for unsafe casting.
- Refactored the `useEffect` logic by introducing an `isDirty` flag and including proper dependencies, ensuring external updates don’t overwrite local edits.
- Removed the `react-hooks/exhaustive-deps` suppression.
The implementation now aligns with the pattern used in `configmap/Details`.

Please let me know if anything else should be improved.

**Comment by iashutoshyadav** [comment]
Hi @illume 

I’ve addressed all the review comments and updated the PR accordingly, including the suggestions around state handling and hook usage. The implementation now follows proper React hook rules, and the logic has been refined to handle edge cases like dirty state and async updates correctly.

Could you please take another look and let me know if anything else needs improvement?

Thanks for your time and review.

File: frontend/src/components/secret/Details.tsx [hunk 1]
```diff
@@ -30,6 +30,86 @@ import { DetailsGrid, SecretField } from '../common/Resource';
 import { SectionBox } from '../common/SectionBox';
 import { NameValueTable, NameValueTableRow } from '../common/SimpleTable';
 
+function SecretDataSection({ item }: { item: Secret }) {
```
Comment (illume) [inline frontend/src/components/secret/Details.tsx]: Could you please move the input type ({item: Secret}) into an interface called SecreteDataSectionProps?

Please use tsdocs to document the item field as well?

**Review by illume — CHANGES_REQUESTED** [review]
Looking good.

Sorry, I just noticed one more thing...

**Comment by iashutoshyadav** [comment]
Hii @illume 

Fixed react-hooks/rules-of-hooks violations in secret/Details.tsx by extracting the inline section() helper into a proper React component SecretDataSection, so hooks like useState, useRef, and useEffect are called inside a valid component body. Also added SecretDataSectionProps interface with TSDoc documentation .

Why AddCluster.stories.tsx was also changed:
While my branch was open, AddCluster.stories.tsx was merged into upstream/main by someone else. GitHub added a needs-rebase label to my PR, so I had to rebase onto upstream/main. That file came into my branch automatically during the rebase, but it had pre-existing ESLint lint violations. Since CI runs lint on all files, it was blocking my PR. I fixed those violations to unblock CI — no logic change, just ESLint fixes.

CI status:
All 11 checks are now passing — build-linux, build-mac, build-windows, lint, tests, storybook, docs, container build. Only tide is pending, which is waiting for the lgtm and approved labels from maintainers.

Please let me know if anything needs to be changed.
Thanks

**Review by illume — APPROVED** [review]
Great work. Much appreciated.

🎉🎈
