### PR TITLE
frontend: ClusterTable: Add cluster name toolip and expand name col

### LINKED ISSUE #4731: All clusters view: Name column cut now with 0.40.1 makes relevant information inaccessible
## Describe the bug
with version 0.40.1 in the "All Clusters" overview, the name column is now cut and in my case with a lot of AWS clusters the most relevant and discerning cluster name information is cut off by default. I can make the full column appear temporarily by switching off other columns, but constant re-draws of the GUI makes this a tedious task.

## To Reproduce
Steps to reproduce the bug:
1. Go to the "Home / All Clusters" view

## Environment (please provide info about your environment):
-  Linux Tarball (Ubuntu 22.04)
 - Headlamp Version: [0.40.1]

## Are you able to fix this issue?
No. 
Of course I may help wherever I can. 

## Additional Context
It seems to be a regression, Headlamp 0.39.0 did not show this behavior.

### LINKED ISSUE #4756: Long cluster names truncated
## Describe the bug
Clusters from kubeconfig with long names, e.g. EKS clusters, only show the beginning of the cluster name, which is often common, so it's not possible to distinguish between different clusters.

## To Reproduce
Steps to reproduce the bug:
1. Add multiple clusters with long names
2. Cluster list on Headlamp main screen shows truncated names. It's not possible to resize the column to see the full name, or see the full name when hovering over.

## Environment (please provide info about your environment):
 - Installation type: Linux-Flatpak
 - Headlamp Version: 0.40.1

## Are you able to fix this issue?
No

## Additional Context

Image

### PR DESCRIPTION
**Pull request by vyncent-t**
## Summary

This PR improves the readability of long cluster names on the Home page cluster table by dynamically expanding the name column and adding a tooltip on hover to display the full cluster name.

## Related Issue

Fixes https://github.com/kubernetes-sigs/headlamp/issues/4731
Fixes https://github.com/kubernetes-sigs/headlamp/issues/4756

## Changes

- Updated `frontend/src/components/App/Home/ClusterTable.tsx`:
  - Added dynamic `gridTemplate` sizing for the name column, expands when any cluster name exceeds 40 characters
  - Added a `Tooltip` on cluster name cells that displays the full cluster name on hover

## Steps to Test

1. Navigate to the Home page
2. Observe the cluster table with short cluster names (the name column should have normal width)
3. Add or configure a cluster with a name longer than 40 characters
4. Observe that the name column expands to take more space
5. Hover over any cluster name and the tooltip should appear showing the full cluster name

## Images

image

### CODE REVIEW

File: frontend/src/components/App/Home/ClusterTable.tsx [hunk 1]
```diff
@@ -242,23 +243,30 @@ export default function ClusterTable({
...
+  const hasLongName = clustersList.some(cluster => cluster.name.length > 40);
+
   return (
     <Table
       columns={[
         {
           id: 'name',
           header: t('Name'),
           accessorKey: 'name',
+          gridTemplate: hasLongName ? 2 : 1,
```
Comment (sniok) [inline frontend/src/components/App/Home/ClusterTable.tsx]: should we have just `gridTemplate: 2` always? I think giving name column more space makes sense. Unless it doesn't look good?

File: frontend/src/components/App/Home/ClusterTable.tsx [hunk 2]
```diff
@@ -242,23 +243,30 @@ export default function ClusterTable({
...
             return (
-              <Link routeName="cluster" params={{ cluster: original.name }}>
-                <ClusterBadge
-                  name={original.name}
-                  icon={appearance.icon}
-                  accentColor={appearance.accentColor}
-                />
-              </Link>
+              <Tooltip title={original.name} arrow>
+                <span>
```
Comment (sniok) [inline frontend/src/components/App/Home/ClusterTable.tsx:258]: is this <span> really needed? I think it might not be necessary

Comment (vyncent-t) [reply frontend/src/components/App/Home/ClusterTable.tsx:258]: It functions just fine without it, but I think it is a nice touch, especially if there are multiple long names and you hover over them

with
image

without
image

File: frontend/src/components/App/Home/ClusterTable.tsx (hunk 1 above)
Comment (vyncent-t) [reply frontend/src/components/App/Home/ClusterTable.tsx]: I thought about leaving at 2 (and maybe expanding to 3 since we technically can have really long names) but for users that do not have longer cluster names it just leaves a lot of empty space there

I'm thinking if people use long names routinely, it should fill out the space more and give a better visual

short names with 2 spacing looks empty
image

our current view w/ short names
image

File: frontend/src/components/App/Home/ClusterTable.tsx (hunk 2 above)
Comment (vyncent-t) [reply frontend/src/components/App/Home/ClusterTable.tsx:258]: It also is helpful for taking screen shots since the mouse isn't usually visible

File: frontend/src/components/App/Home/ClusterTable.tsx (hunk 1 above)
Comment (vyncent-t) [reply frontend/src/components/App/Home/ClusterTable.tsx]: Updated to 2 as per our convo

File: frontend/src/components/App/Home/ClusterTable.tsx (hunk 2 above)
Comment (vyncent-t) [reply frontend/src/components/App/Home/ClusterTable.tsx:258]: keeping as per our convo

**Review by sniok — APPROVED** [review]
thanks!

/lgtm
