### PR TITLE
frontend: Fix resourceFieldRef not resolving sidecar or injection-templated containers

### LINKED ISSUE #5106: Container not found for sidecar-injected containers when displaying env vars with resourceFieldRef
## Describe the bug                                                                                                                                                                                                                
                                                                                                                                                                                                                                     
  When viewing environment variables for a pod that has sidecar containers injected via mutating webhook (e.g. Istio's `istio-proxy`), Headlamp displays "Container not found" for env vars that use `resourceFieldRef` referencing  
  the sidecar container.                                                                                                                                                                                                             
                                                                                                                                                                                                                                     
  For example, Istio injects env vars like:              

  ```yaml
  - name: GOMAXPROCS
    valueFrom:
      resourceFieldRef:
        containerName: istio-proxy
        resource: limits.cpu
  - name: GOMEMLIMIT
    valueFrom:
      resourceFieldRef:                                                                                                                                                                                                              
        containerName: istio-proxy
        resource: limits.memory                                                                                                                                                                                                      
  ```                                                    

  Headlamp resolves `resourceFieldRef` by looking up the container in the pod spec from the API response. However, it appears to look at the **deployment template spec** rather than the **running pod spec**. Since sidecar        
  containers are injected at admission time by a mutating webhook, they exist in the running pod's `spec.containers` but not in the original deployment template.
                                                                                                                                                                                                                                     
  ## Expected behavior                                   

  Headlamp should resolve `resourceFieldRef` using the container list from the actual **Pod** object (`pod.spec.containers` + `pod.spec.initContainers`), not from the Deployment template. This way, sidecar-injected containers    
  like `istio-proxy` would be found and their resource limits displayed correctly.
                                                                                                                                                                                                                                     
  ## To Reproduce                                        

  1. Deploy any workload in a namespace with Istio sidecar injection enabled
  2. Open the pod details in Headlamp
  3. Expand the environment variables section for the `istio-proxy` container
  4. Observe "Container istio-proxy not found" messages for `GOMAXPROCS`, `GOMEMLIMIT`, `ISTIO_CPU_LIMIT` env vars
                                                                                                                                                                                                                                     
  ## Environment
                                                                                                                                                                                                                                     
  - **Headlamp Version:** 0.41.0                         
  - **Installation:** In-cluster (Helm chart)
  - **Kubernetes Version:** 1.33
  - **Istio Version:** 1.26 (sidecar injection via mutating webhook)                                                                                                                                                                 
   
  ## Would you like to fix this bug?                                                                                                                                                                                                 
                                                         
  No

  ## Additional context

  This affects any sidecar injected via mutating admission webhook, not just Istio. The same issue would occur with Linkerd, Dapr, or any other service mesh / sidecar injector.                                                     
   
  Introduced in v0.31.0 via PR #2728.

<img width="836" height="316" alt="Image" src="https://github.com/user-attachments/assets/fd1c6004-99db-4860-9975-c8418125a9cf" />

### PR DESCRIPTION
**Pull request by itvi-1234**
## Summary
Resolves an issue where `resourceFieldRef` environment variables (e.g. `limits.cpu`) failed to correctly map to containers injected at admission time by mutating webhooks (like `istio-proxy` or `istio-init`). 

When viewing Pods or Workloads with external sidecars, users would see the error `Container [name] not found` for any mapped resources. This happened because the internal frontend logic was only searching strictly inside `pod.spec?.containers`, completely omitting `initContainers`, `ephemeralContainers`, and template-based structures like Deployments/Jobs.

Fixes #5106 

## Changes
- Updated `Resource.tsx` (`buildEnvironmentVariables`) to utilize a robust "Gather All Containers" check.
- The `targetContainer` lookup now properly aggregates across `containers`, `initContainers`, `ephemeralContainers`, `template.spec`, and `jobTemplate.spec` before failing.
- Handled TypeScript typing compatibility by casting the generic API wrapper `KubePod` safely.

## How to Test
1. Deploy a workload to an Istio-enabled namespace (or Linkerd/Dapr) ensuring a sidecar like `istio-proxy` is injected.
2. The proxy must use a `valueFrom: resourceFieldRef` environment variable (Istio natively injects `GOMAXPROCS`, `GOMEMLIMIT`, etc.)
3. View the Pod details in Headlamp and expand the environment variables mapping for the proxy container. 
4. Headlamp should cleanly render the CPU / Memory limits without any "Container not found" errors.

### CODE REVIEW

**Comment by itvi-1234** [comment]
Hi @illume @sniok, just a gentle ping for review. Would really appreciate your feedback. Thanks!

File: frontend/src/components/common/Resource/Resource.tsx [hunk 1]
```diff
@@ -995,7 +995,31 @@ function buildEnvironmentVariables(
...
 
         try {
-          const targetContainer = pod.spec?.containers?.find(c => c.name === containerName);
+          const allContainers: any[] = [
+            ...(pod.spec?.containers || []),
+            ...(pod.spec?.initContainers || []),
+            ...(pod.spec?.ephemeralContainers || []),
+          ];
+
+          const templateSpec = (pod.spec as any)?.template?.spec;
```
Comment (sniok) [inline frontend/src/components/common/Resource/Resource.tsx:1004]: the `pod` variable name is very misleading here. this component accepts different kinds of resources, not just pod. in the future that should be reflected in types and variable names a bit better.

I've validated the fix and it does work but this component needs refactor, that can be handled in future PRs though

**Review by sniok — APPROVED** [review]
thanks for the fix!

I've left a comment about how the component needs a bit of a refactor, let me know if that's something you'd be interested in doing. 

/lgtm
